CREATE DATABASE hw1;
USE hw1;

CREATE TABLE ACCOUNTS (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    SURNAME VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(20) NOT NULL UNIQUE,
    EMAIL VARCHAR(40) NOT NULL UNIQUE,
    PASSWORD VARCHAR(60) NOT NULL
);

CREATE TABLE ARTICLES (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(150) NOT NULL UNIQUE,
    CITY VARCHAR(100) NOT NULL,
    CONTENT TEXT NOT NULL,
    AUTHOR INTEGER NOT NULL,
    IMAGE_URL TEXT,
    FOREIGN KEY (AUTHOR) REFERENCES ACCOUNTS(ID)
);

CREATE TABLE LIKES (
    ARTICLE INTEGER NOT NULL,
    USER INTEGER NOT NULL,
    PRIMARY KEY(ARTICLE, USER),
    FOREIGN KEY (ARTICLE) REFERENCES ARTICLES(ID),
    FOREIGN KEY (USER) REFERENCES ACCOUNTS(ID)
);

CREATE TABLE FOLLOWS (
    FOLLOWER INTEGER NOT NULL,
    FOLLOWED INTEGER NOT NULL,
    PRIMARY KEY(FOLLOWER, FOLLOWED),
    FOREIGN KEY(FOLLOWER) REFERENCES ACCOUNTS(ID),
    FOREIGN KEY(FOLLOWED) REFERENCES ACCOUNTS(ID)
);

CREATE TABLE COMMENTS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    AUTHOR INTEGER NOT NULL,
    CONTENT TEXT NOT NULL,
    ARTICLE INTEGER NOT NULL,
    COMMENT_DATE VARCHAR(10) NOT NULL,
    FOREIGN KEY(AUTHOR) REFERENCES ACCOUNTS(ID),
    FOREIGN KEY(ARTICLE) REFERENCES ARTICLES(ID)
);